language: python
python:
- '3.5'
- '3.6'
script: relint **
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: ocotP5Wb+UCtsqMAXOuzCKUabQ6pVkhvRRdNMsJ+MX+Fc6O6fLW90rD5Ny03z29HdvNfedty7hzhGYVdGwOUdMeSy36od1wN7PFZ6cI7Uotn+YBvl249kNdNQFkVcowywUjYi7tuzbl/0VVi1zFCHJvw7Dv0N5LNv7aHeJxuv/9CmOcA+7mEauDjse7zpYxIOO33XLrg2eAZrL1GPZTzrEA7urKBPO6w0s9Z6EUTkEpRYZPBqS6ajCWONNK9Dj65i2GVhEp8SEoAG3ILCiLbM45nJYoUBeL20yG6TliXis4P51JalcgYtq1Ir41vprODA5dWVzgaeS0lemU19ym/Gs+32EmIeMQuJ0QpylmqJ6OjMLTU0QK4up9Eydr824wZ8Q2iZ8zUkaKvrIsLinQ/BSaSnQmz21X0mMXQdDLbI+VmwEOYqaa6liQOK1j1bXSOaCFu6fVV7AiktbCcUeg5NX259VT5+yuAJ49cw3fY7P3pu8+vviNkyKK7APbvhaK4eo4yvGCHGeWaoYrJkb+Vz9yWRathe5nSWzAgOl+fu6N8QCVljMvj1GTt+eVfH8Rr0re7/e/6dv2MiAec+w3K40gp/3J6axMMGfxEQy37+3HCUsgmAGJSFs6uj6KX+HfZTBZIAqyo+KavVos/Ml9zvyf8nTw70FGpay8btc5fyqU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: codingjoe/relint
